name: Test Workflow

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install shopware-cli
        uses: shopware/shopware-cli-action@v1

      - name: Create Shopware project
        run: shopware-cli project create test-project latest

      - name: Delete vendor
        working-directory: test-project
        run: rm -rf vendor

      - name: Build Project
        uses: ./.
        with:
            path: test-project
